/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author skyga
 */
public class XuatChieu_Gui extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJFrame
     */
    public XuatChieu_Gui() {
        initComponents();
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_suatchieu = new javax.swing.JButton();
        txt_suatchieu = new javax.swing.JLabel();
        txt_suatchieu1 = new javax.swing.JLabel();
        btn_suatchieu1 = new javax.swing.JButton();
        txt_suatchieu2 = new javax.swing.JLabel();
        btn_suatchieu2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btn_suatchieu.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btn_suatchieu.setText("08:00");
        btn_suatchieu.setBorder(null);
        btn_suatchieu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_suatchieu.setMargin(new java.awt.Insets(10, 14, 100, 14));
        btn_suatchieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suatchieuActionPerformed(evt);
            }
        });

        txt_suatchieu.setText("10/90 Ghế");

        txt_suatchieu1.setText("78/90 Ghế");

        btn_suatchieu1.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btn_suatchieu1.setText("06:00");
        btn_suatchieu1.setBorder(null);
        btn_suatchieu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_suatchieu1.setMargin(new java.awt.Insets(10, 14, 100, 14));
        btn_suatchieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suatchieu1ActionPerformed(evt);
            }
        });

        txt_suatchieu2.setText("50/90 Ghế");

        btn_suatchieu2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btn_suatchieu2.setText("10:00");
        btn_suatchieu2.setBorder(null);
        btn_suatchieu2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_suatchieu2.setMargin(new java.awt.Insets(10, 14, 100, 14));
        btn_suatchieu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suatchieu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_suatchieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_suatchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_suatchieu2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txt_suatchieu2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txt_suatchieu1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_suatchieu)
                        .addGap(77, 77, 77)))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_suatchieu)
                    .addComponent(txt_suatchieu1))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_suatchieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suatchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(txt_suatchieu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_suatchieu2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suatchieu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suatchieu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_suatchieu2ActionPerformed

    private void btn_suatchieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suatchieu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_suatchieu1ActionPerformed

    private void btn_suatchieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suatchieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_suatchieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XuatChieu_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XuatChieu_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XuatChieu_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XuatChieu_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XuatChieu_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suatchieu;
    private javax.swing.JButton btn_suatchieu1;
    private javax.swing.JButton btn_suatchieu2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_suatchieu;
    private javax.swing.JLabel txt_suatchieu1;
    private javax.swing.JLabel txt_suatchieu2;
    // End of variables declaration//GEN-END:variables
}
